//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.4200
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proj4Net.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Proj4Net.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die testName,testMethod,srcCrsAuth,srcCrs,tgtCrsAuth,tgtCrs,srcOrd1,srcOrd2,srcOrd3,tgtOrd1,tgtOrd2,tgtOrd3,tolOrd1,tolOrd2,tolOrd3,using,dataSource,dataCmnts,maintenanceCmnts
        ///#&quot;NAD83 State Plane CS - AK 1 &quot;,&quot;Proj4j&quot;,&quot;EPSG&quot;,&quot;4269&quot;,&quot;ESRI&quot;,&quot;102631&quot;,-134.0,55.0,&quot;&quot;,2616018.154,1156379.643,&quot;&quot;,0.1,0.1,0.0,&quot;&quot;,&quot;PROJ4 test83&quot;,&quot;&quot;,&quot;&quot;
        ///#&quot;NAD83 State Plane CS - AK 1 &quot;,&quot;Proj4j&quot;,&quot;EPSG&quot;,&quot;4269&quot;,&quot;ESRI&quot;,&quot;102631&quot;,-133.66666666666666,57.0,&quot;&quot;,2685941.919,1886799.668,&quot;&quot;,0.1,0.1,0.0,&quot;&quot;,&quot;PROJ4 test83&quot;,&quot;&quot;,&quot;Bug in Proj4J Obl Merc&quot;
        ///#&quot;NA [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PROJ4_SPCS_EPSG_nad83 {
            get {
                return ResourceManager.GetString("PROJ4_SPCS_EPSG_nad83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die testName,testMethod,srcCrsAuth,srcCrs,tgtCrsAuth,tgtCrs,srcOrd1,srcOrd2,srcOrd3,tgtOrd1,tgtOrd2,tgtOrd3,tolOrd1,tolOrd2,tolOrd3,using,dataSource,dataCmnts,maintenanceCmnts
        ///&quot;NAD83 State Plane CS - AK 1 &quot;,&quot;Proj4j&quot;,&quot;EPSG&quot;,&quot;4269&quot;,&quot;ESRI&quot;,&quot;102631&quot;,-134.0,55.0,&quot;&quot;,2616018.154,1156379.643,&quot;&quot;,0.1,0.1,0.0,&quot;&quot;,&quot;PROJ4 test83&quot;,&quot;&quot;,&quot;Bug in Proj4J Obl Merc&quot;
        ///&quot;NAD83 State Plane CS - AK 1 &quot;,&quot;Proj4j&quot;,&quot;EPSG&quot;,&quot;4269&quot;,&quot;ESRI&quot;,&quot;102631&quot;,-133.66666666666666,57.0,&quot;&quot;,2685941.919,1886799.668,&quot;&quot;,0.1,0.1,0.0,&quot;&quot;,&quot;PROJ4 test83&quot;,&quot;&quot;,&quot;Bug in Pr [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PROJ4_SPCS_ESRI_nad83 {
            get {
                return ResourceManager.GetString("PROJ4_SPCS_ESRI_nad83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die testName,testMethod,srcCrsAuth,srcCrs,tgtCrsAuth,tgtCrs,srcOrd1,srcOrd2,srcOrd3,tgtOrd1,tgtOrd2,tgtOrd3,tolOrd1,tolOrd2,tolOrd3,using,dataSource,dataCmnts,maintenanceCmnts
        ///&quot;NAD27 State Plane CS - AK 1 &quot;,&quot;Proj4j&quot;,&quot;EPSG&quot;,&quot;4267&quot;,&quot;EPSG&quot;,&quot;26731&quot;,-134.0,55.0,,2615716.535,1156768.938,,0.1,0.1,,&quot;&quot;,&quot;PROJ4 test27&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;NAD27 State Plane CS - AK 1 &quot;,&quot;Proj4j&quot;,&quot;EPSG&quot;,&quot;4267&quot;,&quot;EPSG&quot;,&quot;26731&quot;,-133.66666666666666,57.0,,2685642.815,1887198.473,,0.1,0.1,,&quot;&quot;,&quot;PROJ4 test27&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;NAD27 State Plane CS - AK 1 &quot;,&quot;Proj4j&quot;,&quot;EPS [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PROJ4_SPCS_nad27 {
            get {
                return ResourceManager.GetString("PROJ4_SPCS_nad27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die # Version: 00.12.00
        ///# This file is provided as part of the MetaCRS Project at the OSGeo. It is released into the public domain.
        ///# You use this file AT YOUR OWN RISK! The OSGeo, OSGeo Members, MetaCRS Members, and contributors to this file do not 
        ///# make any warranties or statements about its accuracy or correctness.
        ///testName,testMethod,srcCrsAuth,srcCrs,tgtCrsAuth,tgtCrs,srcOrd1,srcOrd2,srcOrd3,tgtOrd1,tgtOrd2,tgtOrd3,tolOrd1,tolOrd2,tolOrd3,using,dataSource,dataCmnts,maintenanceCmnts
        ///WGS84 Geographic 2D to [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string TestData {
            get {
                return ResourceManager.GetString("TestData", resourceCulture);
            }
        }
    }
}
